use mydb;
SELECT * FROM mydb.Ingredient;
INSERT INTO Ingredient (name_ingredient, quantity) VALUES ("sauce tomate", "900");
INSERT INTO Ingredient (name_ingredient, quantity) VALUES ("crèche fraiche", "900");
INSERT INTO Ingredient (name_ingredient, quantity) VALUES ("mozarella", "980");
INSERT INTO Ingredient (name_ingredient, quantity) VALUES ("pâte à pizza", "200");
INSERT INTO Ingredient (name_ingredient, quantity) VALUES ("Poulet émincé", "500");
INSERT INTO Ingredient (name_ingredient, quantity) VALUES ("Salami Piquante", "500");
INSERT INTO Ingredient (name_ingredient, quantity) VALUES ("Parma Ham", "500");
INSERT INTO Ingredient (name_ingredient, quantity) VALUES ("Lardon", "500");
INSERT INTO Ingredient (name_ingredient, quantity) VALUES ("Pomme de terre", "500");
